//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalemTanimlari.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SYS_ItemInformation
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string RelatedCompany { get; set; }
        public Nullable<int> ItemSequence { get; set; }
        public string ItemCurrency { get; set; }
        public string CurrencyRate { get; set; }
        public string ItemType { get; set; }
        public string ReportLot { get; set; }
        public string ApportionProcedure { get; set; }
        public string CopyFormula { get; set; }
        public Nullable<bool> RegulatoryArea { get; set; }
        public Nullable<bool> GrossProfitAndLoss { get; set; }
        public Nullable<bool> CutCreditAdvice { get; set; }
        public Nullable<bool> ExpeditionaryRevenueCostItem { get; set; }
        public Nullable<bool> InternalAbstractAccount { get; set; }
        public string InvoiceItemDisclosures { get; set; }
        public Nullable<bool> RevenueItem { get; set; }
        public Nullable<bool> CostItem { get; set; }
        public string RevenueAccount { get; set; }
        public string CostAccount { get; set; }
        public string ExpenceCenterAccount { get; set; }
        public string RevenueVatAccount { get; set; }
        public string CostVatAccount { get; set; }
        public Nullable<decimal> RevenueRateOfVat { get; set; }
        public Nullable<decimal> CostRateOfVat { get; set; }
        public Nullable<bool> Modules { get; set; }
    }
}
